### PR TITLE
xsd-fu: Use multi-index for C++ reference lists

### PR DESCRIPTION
**Pull request by ghost**
boost::multi_index_container is used to index elements by both
index number (insertion order) and value (pointer location).
This allows access by index and fast lookup without the need
for an O(n) list traversal.

This is similar to the Java ReferenceList but does not implement
a container in its own right; it's just a specialisation of an
existing multi-indexing container implementation as a typedef.
The code generator has been updated to emit the new container
types in place of std::vector, and the C++ code templates
adjusted to use them for fast lookups.

Tested on Ubuntu 12.04, 14.10 and MacOS for both C++98 and C++11 builds.

### CODE REVIEW

**Comment by ghost** [comment]
If you would prefer these as separate PRs opened directly against openmicroscopy/bioformats, just let me know.

Working on ubuntu 12.04 and travis will now pass.

**Comment by ghost** [comment]
Travis green: https://travis-ci.org/rleigh-dundee/bioformats/builds/43783756

**Comment by ghost** [comment]
Closing in favour of https://github.com/openmicroscopy/bioformats/pull/1482
